server:
  port: 8080 #Tomcat端口
spring:
  dubbo:
    application:
      name: dubbo-consumer #应用名
    registry:
      address: zookeeper://192.168.178.143:2181 #zookeeper地址
      protocol: zookeeper
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口